language: go
go:
  - 1.15
env:
  global:
    - secure: "DvI7JE65KOJCKJNqdLR+2SueBx883lJFaYogVIXzsSCpxdJxC+5spXZ9jj8JmTHhaKiB8BcXFwqjXoCfwTL81Mv/jv1qAzn1DGuabNuYjbNX8kD+WsXulu2xcVQzbZHclKo7jYKOnXYlm/xu4JJLq5vhFxYGCWQZLRE1j+ApJgeVNrYxbUxvEXuZWvSjxm4g7ilnX9PxDHeQEaRr7rhLIuUv01OOZ3/jg2JxGAE1ZC5gHOI6s3GJTG5fW2BzHgMGxio7HIo8Giu2c63VxZicpElNC+qqcLubTIXtWj9baUXjroYrkmrsG36Wrq6TQk30rX5op2HQesG9nsOKpQkqIOxqLyR8xERAz54m8ZL7SPab7gz1HLJEJlu2oBnQzylJe7TzpaQizqIdtd3ui0uKMTfF7yeED1Wfn/eor4zd63LXZBPhga0gW+9VDIFYBBATQ4kmW/G5w/6hO6bjFKdeHi7Q4wi6sEanGb0BLsKdvL6wgbGbXVAOUKL0+NLRwgEm8n4HSaCcLFcKlOanLmxvz1v2qkz/vDrtr7Ap+CT1BX4sNPmACINzvP0PdERo0KBfq9mWEd3YNIIYO0uwqRo12lP6Th+dDiX7V7V/CHbD0J5F0nhbwy45wnNLSnSG0aP9sFIbrxi1RcfWaaMxE3bY/qdfSzDMXxbMcFQg+ZpEhnA="
jobs:
  include:
    - stage: test
      name: Run tests
      script:
        - make test
    - stage: build
      script:
        - make build
      deploy:
        provider: releases
        skip_cleanup: true
        name: "Shox $TRAVIS_TAG"
        edge: true
        file:
          - bin/darwin/shox-darwin-amd64
          - bin/linux/shox-linux-amd64
        on:
          repo: liamg/shox
          tags: true
